[env]
TERM = "xterm-256color"

[general]
import = [
  "~/.config/alacritty/themes/catppuccin/catppuccin-mocha.toml"
]

[window]
dimensions = { columns = 80, lines = 24}
opacity = 0.97

[font]
normal = { family = "Fira Code Nerd Font", style = "Regular" }
